@extends('layouts.master')

<style type="text/css">
    @keyframes ldio-70zupg3by86 {
        0% {
            opacity: 1
        }

        100% {
            opacity: 0
        }
    }

    .ldio-70zupg3by86 div {
        left: 47px;
        top: 24px;
        position: absolute;
        animation: ldio-70zupg3by86 linear 1s infinite;
        background: #555555;
        width: 6px;
        height: 12px;
        border-radius: 3px / 4.5600000000000005px;
        transform-origin: 3px 26px;
    }

    .ldio-70zupg3by86 div:nth-child(1) {
        transform: rotate(0deg);
        animation-delay: -0.9166666666666666s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(2) {
        transform: rotate(30deg);
        animation-delay: -0.8333333333333334s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(3) {
        transform: rotate(60deg);
        animation-delay: -0.75s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(4) {
        transform: rotate(90deg);
        animation-delay: -0.6666666666666666s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(5) {
        transform: rotate(120deg);
        animation-delay: -0.5833333333333334s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(6) {
        transform: rotate(150deg);
        animation-delay: -0.5s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(7) {
        transform: rotate(180deg);
        animation-delay: -0.4166666666666667s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(8) {
        transform: rotate(210deg);
        animation-delay: -0.3333333333333333s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(9) {
        transform: rotate(240deg);
        animation-delay: -0.25s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(10) {
        transform: rotate(270deg);
        animation-delay: -0.16666666666666666s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(11) {
        transform: rotate(300deg);
        animation-delay: -0.08333333333333333s;
        background: #555555;
    }

    .ldio-70zupg3by86 div:nth-child(12) {
        transform: rotate(330deg);
        animation-delay: 0s;
        background: #555555;
    }

    .loadingio-spinner-spinner-og8ww2g8awq {
        width: 38px;
        height: 38px;
        display: inline-block;
        overflow: hidden;
        background: rgba(NaN, NaN, NaN, 0);
    }

    .ldio-70zupg3by86 {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.38);
        backface-visibility: hidden;
        transform-origin: 0 0;
        /* see note above */
    }

    .ldio-70zupg3by86 div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#page-top"><img src="{{ asset('assets/img/tlx_logo.png') }}"
                    style="width: 100px;"></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#about">Beranda</a></li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#services">Cek Resi</a>
                    </li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#services">Cek
                            Ongkir</a></li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#services">Agen</a></li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#portfolio">Tentang
                            Kami</a></li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#services">Pengajuan
                            Klaim</a></li>
                    <li style="white-space: nowrap; font-family:titillium-semi;" class="nav-item"><a class="nav-link"
                            href="#contact">Kontak</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header>
        <!-- This div is  intentionally blank. It creates the transparent black overlay over the video which you can modify in the CSS -->
        <div class="overlay"></div>

        <!-- The HTML5 video element that will create the background video on the header -->
        <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
            <source src="{{ asset('assets/files/video/compro.mp4') }}" type="video/mp4">
        </video>

        <!-- The header content -->
        <div class="container h-100">
            <div class="d-flex h-100 text-center align-items-center">
                <div class="w-100 text-white">
                    {{-- <h1 class="display-3">Halo</h1>
                    <p class="lead mb-0">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quaerat, a.</p> --}}
                </div>
            </div>
        </div>
    </header>

    <section class="bg-white" style="border-radius: 10%; background: rgba(255, 255, 255, 0.9);box-shadow: 4px 4px 20px rgba(0, 0, 0, 0.1);
                border-radius: 20px; font-family:titillium-semi;">
        <div class="text-center">
            <div class="py-5" style="margin: 4%">

                <h3 class="h4 mb-2" style="font-family: gotham;">Pengirimanmu Aman, Cari Posisinya</h3>
                <p class="text-muted mb-0">Masukkan NOMOR RESI atau AWB atau KODE BOOKING</p>
                <input type="text" id="searching" name="searching" style="text-align: center;" class="form-control"
                    placeholder="622xxxxxxxxx">
                <button type="submit" id="search-btn" class="btn btn-info mt-2">
                    <div id="search-text">SEARCH</div>
                    <div id="loading" style="display: none" class="loadingio-spinner-spinner-og8ww2g8awq">
                        <div class="ldio-70zupg3by86">
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>

                </button>

            </div>
        </div>
    </section>

    <!-- Tracking -->
    <div class="container px-4 px-lg-5">
        <div class="timeline mx-auto my-5">

            {{-- {{-- <div class="entry">
                <div class="title">
                </div>
                <div class="body">
                    <p>Voluptatibus veniam ea reprehenderit atque reiciendis non laborum adipisci ipsa pariatur omnis.
                    </p>

                </div>
            </div> --}}

            {{-- <div class="entry">
            <div class="title">
                <p>Selasa</p>
                <h6>23 May 2022</h6>
            </div>
            <div class="body">
                <p>Voluptatibus veniam ea reprehenderit atque reiciendis non laborum adipisci ipsa pariatur omnis.
                </p>

            </div>
        </div> --}}
            {{-- <div class="entry">
            <div class="title">
            </div>
            <div class="body">
                <p>Voluptatibus veniam ea reprehenderit atque reiciendis non laborum adipisci ipsa pariatur omnis.
                </p>

            </div>
        </div>
        <div class="entry">
            <div class="title">
            </div>
            <div class="body">
                <p>Voluptatibus veniam ea reprehenderit atque reiciendis non laborum adipisci ipsa pariatur omnis.
                </p>

            </div>
        </div> --}}
        </div>
    </div>


    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ asset('assets/files/banner/1.jpg') }}" class="d-block w-100" alt="...">
                {{-- <div class="carousel-caption">
                    <h5>First slide label</h5>
                    <p>Some representative placeholder content for the first slide.</p>
                </div> --}}
            </div>
            <div class="carousel-item">
                <img src="{{ asset('assets/files/banner/2.jpg') }}" class="d-block w-100" alt="...">
                {{-- <div class="carousel-caption">
                    <h5>Second slide label</h5>
                    <p>Some representative placeholder content for the second slide.</p>
                </div> --}}
            </div>
            <div class="carousel-item">
                <img src="{{ asset('assets/files/banner/3.jpg') }}" class="d-block w-100" alt="...">
                {{-- <div class="carousel-caption">
                    <h5>Third slide label</h5>
                    <p>Some representative placeholder content for the third slide.</p>
                </div> --}}
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <section class="page-section bg-light" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">Mengapa Memilih TLX</h2>
            <hr class="divider" />
            <div class="news-slider">
                <div class="text-center rounded bg-white mx-3 py-5">
                    <div class="mt-2">
                        <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Safe and Reliable</h3>
                        <p class="text-muted mb-0">Our themes are updated regularly to keep them bug free!</p>
                    </div>
                </div>
                <div class="text-center rounded bg-white mx-3 py-5">
                    <div class="mt-2">
                        <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Closer To You</h3>
                        <p class="text-muted mb-0">All dependencies are kept current to keep things fresh.</p>
                    </div>
                </div>
                <div class="text-center rounded bg-white mx-3 py-5">
                    <div class="mt-2">
                        <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Worldwide Connected</h3>
                        <p class="text-muted mb-0">You can use this design as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="text-center rounded bg-white mx-3 py-5">
                    <div class="mt-2">
                        <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">Smile... Your Package is Guaranteed</h3>
                        <p class="text-muted mb-0">Is it really open source if it's not made with love?</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Portfolio-->
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.8171679117722!2d107.5723156508684!3d-6.912451794980864!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68e797205cb175%3A0xd2176da4fcb21033!2sTLX%20(KIRIM%20PAKET%20KE%20LUAR%20NEGERI)!5e0!3m2!1sen!2sid!4v1612328872682!5m2!1sen!2sid"
        width="100%" height="600" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
    </iframe>
    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="info">
                        <h4 style="color: #000000; font-family: titillium-semi"><strong>TENTANG KAMI</strong></h4>
                        <p class="text-justify" style="color: #000000; font-size:16px; font-family: titillium-semi">
                            Memulai bisnis sejak 2010, kami sebagai penyedia jasa kurir internasional yang handal,
                            menjamin pengiriman anda akan sampai di negara tujuan dengan baik karena kami memiliki
                            relasi dengan partner-partner dari dalam maupun luar negeri.
                        </p><br>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="info">
                        <h4 style="color: #000000; font-family: titillium-semi"><strong>KANTOR PUSAT</strong></h4>
                        <p class="text-left" style="color: #000000; font-size:16px; font-family: titillium-semi">
                            JL. RAJAWALI BARAT NO. 89, BANDUNG 40184, INDONESIA
                        </p>
                    </div>
                </div>
                <div class="col-md-6">

                </div>
            </div>
            <hr style="border: 1px solid white;">
        </div>
        <center>
            <div class="copyright" style="font-size:22px; color: #000000; font-family: titillium-semi;">
                <strong>
                    Copyright ©
                    <script>
                        document.write(new Date().getFullYear())
                    </script> PT. DOKUMEN PAKET EKSPRES
                </strong>
            </div>
        </center>
    </footer>

    @push('script')
    <script>
        let day = [
            'Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'
        ]

        let month = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']

        $('#search-btn').on('click',function(e){
            e.preventDefault()
            $("#search-text").hide()
            $('#loading').show()
            let searching = $('#searching').val()
            console.log(searching)
            $.get('http://localhost:8000/getTrackChoir/'+searching,function(data){
                $('.entry').remove()
                if(JSON.parse(data).datachoir == undefined){
                    console.log('undefinedddd ' + searching)
                    $.get("/api/checkawb?searching="+searching,function(val){
                        val.forEach(e=>{
                            $('.timeline').append(`<div class="entry">
                               
                                <div class="body">
                                    <p>${e.status_eng}
                                    </p>
                            
                                </div>
                            </div>`)
                        })
                    })
                    // $.get("/api/checkawb?searching="searching,function(val){
                    //     console.log(val)
                    // })
                        // $.get("/api/checkawb?searching="searching,function(val){
                        //     console.log(val)
                        // })
                }else{
                    JSON.parse(data).datachoir.forEach(z=>{
                    $('.timeline').append(`<div class="entry">
                        <div class="title">
                            <p>${day[new Date(z.shipment_date).getDay()]}</p>
                            <h6>${new Date(z.shipment_date).getDate()} ${month[new Date(z.shipment_date).getMonth()]} ${new
                                Date(z.shipment_date).getFullYear()}</h6>
                        </div>
                        <div class="body">
                            <p>${z.notes}
                            </p>
                    
                        </div>
                    </div>`)
                    })
                }
                
                
$("#search-text").show()
$('#loading').hide()
                
            })
        })
    </script>
    @endpush